db_lab2 <- read.csv(file.choose())
View(db_lab2)
attach(db_lab2)
filter = dplyr::select(db_lab2, Khoi A, Khoi B, KhoiC, KhoiA1)
filter = dplyr::select(db_lab2, Khoi A, Khoi B, KhoiC, KhoiA1)
filter = dplyr::select(db_lab2, KhoiA, KhoiB, KhoiC, KhoiA1)
View(filter)
group = stack(filter)
group_remove_empty =na.omit(group)
sample_1000 = dplyr::sample_n(group_remove_empty, 1000)
View(sample_1000)
colnames(sample_1000) <- c('Diem', 'Khoi')
write.csv(file.choose())
db_lab2_4= read.csv(file.choose())
View(db_lab2_4)
View(db_lab2_4)
remove(db_lab2_4)
write.csv(sample_1000, file.choose())
db_lab2_4 = read.csv(file.choose())
View(db_lab2_4)
require(car)
attach(db_lab2_4)
leveneTest(Diem, Khoi, center=mean)
rs =  aov(Diem~Khoi, data = db_lab2_4)
summary(rs)
View(group_remove_empty)
